version: "3.9"

services:
  app:    
    container_name: book_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure
  db:
    container_name: books_db
    image: postgres:13.3-alpine
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_DB='${DB_NAME}'
      - POSTGRES_USER='${DB_USER}'
      - POSTGRES_PASSWORD='${DB_PASSWORD}'
    volumes:
      - node_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
volumes:
  node_db_data: {}